name: e2e
on: [push]
jobs:
  basic-ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        uses: ./
        with:
          working-directory: .
          build: npx cypress info