name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and run tests
      working-directory: ./client
      run: |
        npm install
        npm install react-scripts
        npx react-scripts build
        npx react-scripts test --testPathIgnorePatterns=src/test/cypress

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3001
          working-directory: ./client

  test-java-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Maven
        run: |
          npm install
          npm install react-scripts
          npx react-scripts build $
          ../client/npx react-scripts
          mvn --batch-mode --update-snapshots verify
        working-directory: ./java-server